### ISSUE TITLE
Output csv directory should be created if it does not exist

### ISSUE THREAD

**Issue by philipmat** [philipmat/discogs-xml2db#108]
```
ubuntu@ip-172-31-39-147:~/code/discogs-xml2db$ python3 run.py --export label dump-dir csv-dir
Traceback (most recent call last):
File "run.py", line 23, in 
sys.exit(main(arguments))
File "/home/ubuntu/code/discogs-xml2db/discogsxml2db/exporter.py", line 324, in main
exporter.export()
File "/home/ubuntu/code/discogs-xml2db/discogsxml2db/exporter.py", line 71, in export
return self.export_from_file(self.openfile())
File "/home/ubuntu/code/discogs-xml2db/discogsxml2db/exporter.py", line 114, in export_from_file
operations = self.build_ops()
File "/home/ubuntu/code/discogs-xml2db/discogsxml2db/exporter.py", line 90, in build_ops
out_file_obj = open_func(os.path.join(self.out_dir, fname), 'wt', newline='', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: 'csv-dir/label.csv'
```

**Comment by philipmat** [comment]
Fixed with commit e6efbe2e039f0a845cb6839ae35ff39a60cd4950
