### ISSUE TITLE
run.py failing on parsing  discogs_20200901_releases.xml.gz, maybe an error in xmlfile

### ISSUE THREAD

**Issue by ijabz** [philipmat/discogs-xml2db#121]
run.py failing on parsing  discogs_20200901_releases.xml.gz, maybe an error in xmlfile

ubuntu@ip-172-31-36-94:~/code/discogs-xml2db$ python3 run.py --export artist --export label --export master --export release  . csv-dir
Processing     artists: 7094184artists [11:52, 9958.96artists/s]
Processing      labels: 1584254labels [02:18, 11424.83labels/s]
Processing     masters: 1747247masters [06:14, 4660.01masters/s]
Processing    releases:  31%|█████████████████████████████████████████▋                                                                                              | 2603682/8500000 [33:38<1:16:11, 1289.82releases/s]
Traceback (most recent call last):
  File "run.py", line 23, in <module>
    sys.exit(main(arguments))
  File "/home/ubuntu/code/discogs-xml2db/discogsxml2db/exporter.py", line 325, in main
    exporter.export()
  File "/home/ubuntu/code/discogs-xml2db/discogsxml2db/exporter.py", line 71, in export
    return self.export_from_file(self.openfile())
  File "/home/ubuntu/code/discogs-xml2db/discogsxml2db/exporter.py", line 123, in export_from_file
    for cnt, entity in enumerate(filter(self.validate, self.parser.parse(fp)), start=1):
  File "/home/ubuntu/code/discogs-xml2db/discogsxml2db/parser.py", line 83, in parse
    for event, element in etree.iterparse(fp, tag=self.entity_tag):
  File "src/lxml/iterparse.pxi", line 209, in lxml.etree.iterparse.__next__
  File "src/lxml/iterparse.pxi", line 194, in lxml.etree.iterparse.__next__
  File "src/lxml/iterparse.pxi", line 229, in lxml.etree.iterparse._read_more_events
  File "src/lxml/parser.pxi", line 1384, in lxml.etree._FeedParser.feed
  File "src/lxml/parser.pxi", line 606, in lxml.etree._ParserContext._handleParseResult
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "/home/ubuntu/code/discogs-xml2db/discogs_20200901_releases.xml.gz", line 34997079
lxml.etree.XMLSyntaxError: expected '>', line 34997079, column 1626

**Comment by philipmat** [comment]
I'll try to investigate, meanwhile could you take a look at the xml file and see if there's something weird at "line 34997079, column 1626"?

**Comment by ijabz** [comment]
Maybe my download was corrupt (i didnt checksum it). I redownloaded and have been running run.py for quite some time and it is yet to fail, will let you know when completes or fails.

**Comment by ijabz** [comment]
Must have been an error with downloading the files, working now.
