### ISSUE TITLE
Release.artist is missing from some datasets

### ISSUE THREAD

**Issue by kenanM** [philipmat/discogs-xml2db#42]
When exporting the 20131201_releases.xml file I've found that some entries don't have the artist attribute.

I'm not sure if this issue is unique to this 20131201_releases.xml file and so should be considered a bug with the data or code.

## Stacktrace
```
Namespace(data_quality=None, date='20131201', file=[], ignore_unknown_tags=True, n=None, output='mongo', params='file://output')
Traceback (most recent call last):
  File "discogsparser.py", line 223, in <module>
    main(sys.argv[1:])
  File "discogsparser.py", line 217, in main
    parseReleases(parser, exporter)
  File "discogsparser.py", line 128, in parseReleases
    parser.parse(release_file)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 207, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 304, in end_element
    self._cont_handler.endElement(name)
  File "/home/kenan/workspace/discogs-xml2db/discogsreleaseparser.py", line 309, in endElement
    self.exporter.storeRelease(self.release)
  File "/home/kenan/workspace/discogs-xml2db/mongodbexporter.py", line 243, in storeRelease
    if release.artist:
AttributeError: Release instance has no attribute 'artist'
```

**Comment by ijabz** [comment]
Closed this was fixed by submitter
