### ISSUE TITLE
Latest dump throwing an error

### ISSUE THREAD

**Issue by hmac2222** [philipmat/discogs-xml2db#86]
It ran for about 50 minutes, then it threw this error. Any ideas?

> Error executing: INSERT INTO releases_images(type, height, width, release_id) VALUES ('primary', '600', '600', 1);
Traceback (most recent call last):
  File "discogsparser.py", line 139, in <module>
    main(sys.argv[1:])
  File "discogsparser.py", line 133, in main
    parseReleases(parser, exporter)
  File "discogsparser.py", line 92, in parseReleases
    parseEntities(parser, exporter, 'releases', ReleaseHandler)
  File "discogsparser.py", line 75, in parseEntities
    parser.parse(f)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 320, in end_element
    self._cont_handler.endElement(name)
  File "/downloads/discogs-xml2db-master/parsers/discogsreleaseparser.py", line 336, in endElement
    self.exporter.storeRelease(self.release)
  File "/downloads/discogs-xml2db-master/exporters/postgresexporter.py", line 205, in storeRelease
    values)
  File "/downloads/discogs-xml2db-master/exporters/postgresexporter.py", line 92, in runQuery
    self.execute(query, values)
  File "/downloads/discogs-xml2db-master/exporters/postgresexporter.py", line 70, in execute
    raise PostgresExporter.ExecuteError(e.args)
exporters.postgresexporter.ExecuteError: duplicate key value violates unique constraint "releases_images_pkey"
DETAIL:  Key (release_id, type)=(1, primary) already exists.

**Comment by drone1** [comment]
I get an error when parsing the JSON this project generates for releases. Seems to have a format error. Related? Importing directly into Mongo is soooooo sloowwww

**Comment by philipmat** [comment]
Interesting - looks as if we have duplicate entries.

@drone1 - yours is a different issue. Could you please open an issue and provide as much info as you can? "I get an error" is not getting us anywhere.

**Comment by drone1** [comment]
If you don’t know what the error I got was, how do you know it’s a
different issue?

You might want to give it a try yourself as I probably won’t be able to
give you a specific error anytime soon, but FWIW I believe mongoimport’s
JSON parser failed while reading the generated releases JSON.

**Comment by ijabz** [comment]
Latest dump works fine for me (with speedup version) so I think we can probably close this ?

**Comment by berz** [comment]
Indeed, I did not run into trouble importing the dumps for 2019-07, 2020-01 or 2020-04 using the latest version of this code. It seems this issue can be closed.

**Comment by ijabz** [comment]
okay, closing.
