### ISSUE TITLE
Cannot Parse Latest Data Dump (Releases)

### ISSUE THREAD

**Issue by saumya-cc** [philipmat/discogs-xml2db#91]
Running the discogsparser runs into an error: 

python discogsparser.py -o json discogs_20171201_releases.xml

Traceback (most recent call last):
  File "discogsparser.py", line 139, in <module>
    main(sys.argv[1:])
  File "discogsparser.py", line 133, in main
    parseReleases(parser, exporter)
  File "discogsparser.py", line 92, in parseReleases
    parseEntities(parser, exporter, 'releases', ReleaseHandler)
  File "discogsparser.py", line 75, in parseEntities
    parser.parse(f)
  File "/anaconda/lib/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/anaconda/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/anaconda/lib/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/anaconda/lib/python2.7/xml/sax/expatreader.py", line 339, in end_element
    self._cont_handler.endElement(name)
  File /Downloads/discogs-xml2db/parsers/discogsreleaseparser.py", line 325, in endElement
    self.release.master_id = int(self.buffer)
ValueError: invalid literal for int() with base 10: 'Correct'

**Comment by ijabz** [comment]
Yes I can confirm I had same issue with 20171203 dataset and I think its because in release data we now have:

<master_id is_main_release="true">713738</master_id>

instead of just

<master_id>713738</master_id>

and problem persists in 2018001 dataset

so will need change in discgsreleaseparser.py, proably at line 

 elif name == 'master_id':
                        self.release.master_id = int(self.buffer)

but my python knowledge is limited so not sure how to do this.

**Comment by ijabz** [comment]
Closing as temporary issue with one datadump
